# -*- coding: utf-8 -*-
"""Correlation-Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ra2fpdWD2o-Iyk7DbyUktBcSuzj5B4bH
"""

# PYTHON MODULES
# import user-installed modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# pandas options
pd.set_option('display.max_rows', 100)

# use !wget -nc 'github path' to pull the happiness data

#load data from github
!wget "https://raw.githubusercontent.com/emilyyyyyleeeee/ITP487_Correlation_Analysis_IC/main/happyscore_income.csv"

happiness_income_log = pd.read_csv('.csv')

# view columns and null counts for each column in the data frame
print(happiness_income_log.columns)
print(happiness_income_log.info())

# shape of the data frame
# happiness income log:
print("Happiness Income Log Shpae:")
print(happiness_income_log.shape)

# show first five rows of the data frame
happiness_income_log.head()

# clean the happiness income log
df = happiness_income_log[['GDP', 'happyScore']]
print(df.head())

print("Shape before dropping duplicates and unneeded columns: ")
print(df.shape)

df = df.drop_duplicates()
df = df.dropna()
print("Shape after dropping duplicates and unneeded columns: ")
print(df.shape)

# To find the correlation among
# the columns using pearson method
df.corr(method ='pearson')

# To find the correlation among
# the columns using kendall method
df.corr(method='kendall')

# To find the correlation among
# the columns using spearman method
df.corr(method='spearman')

df_analysis = happiness_income_log[['income_inequality', 'std_satisfaction']]
df_analysis = df_analysis.drop_duplicates().dropna()
correlation_result = df_analysis.corr(method='pearson')
print(correlation_result)
